### ISSUE TITLE
ender - doesn't maintain methods when using methods like last()

### ISSUE THREAD

**Issue by dawnerd** [ded/bonzo#1]
Example:

```
 $('.slide', this.mainStage).last().animate({....});
```

Brings the error that animate() is not a method. Workaround right now is to wrap $('.slide', this.mainStage).last() in another $().

Would be nice if last returned an object that is directly chainable with other methods like .animate()

**Comment by ded** [comment]
I originally wrote <code>first()</code> and <code>last()</code> with that design, however last night i implemented <code>next()</code> and <code>previous()</code> with the functionality that you're talking about (continuing the chain). And honestly, for Ender's sake, I think if someone really wanted the first element, they would use the shorter version $('div')[0].

Luckily this is an easy patch. Should be in momentarily.

**Comment by dawnerd** [comment]
Oh, ho, ho! using [0] is much shorter. I was using elements[0] before.

Thanks, this clears a lot up.

**Comment by ded** [comment]
https://github.com/ded/bonzo/commit/e1aa2ab7823237d8adc2f9e991ebd7949bb43b5a

**Comment by fat** [comment]
how do you feel about wrapping all return values that are either elements or arrays, in an ender object?

**Comment by ded** [comment]
reason?

**Comment by fat** [comment]
to make chaining easier... (not to always have to do it in bridges) ...

**Comment by ded** [comment]
i think some are designed to return what you really want. eg:

```
$('p').offset()
$('input').first().attr('checked')
```

**Comment by fat** [comment]
sure... in the bridges right?

**Comment by ded** [comment]
otherwise the rest already do return itself.

**Comment by ded** [comment]
Bonzo itself does this.

```
bonzo(elements).first().css('color', 'red');
```

**Comment by fat** [comment]
right -- i was just wondering if you thought it was good idea to move functionality into ender... is there ever a time you wouldn't want an array or a nodelist wrapped with ender?

**Comment by ded** [comment]
after an in-person discussion we decided this belongs in the bridge files.
