### ISSUE TITLE
$("").html method in IE 8

### ISSUE THREAD

**Issue by hwa** [ded/bonzo#10]
I found that in IE 8, <code>$("form select").html("<option>op_1<option>")</code> would change <code><select></code>'s innerHTML to be <code>op_1</option></code>. Rather peculiar.

**Comment by ded** [comment]
wow. ok. will investigate.

**Comment by ded** [comment]
Confirmed.
http://cl.ly/3K230o22242E1a3H1k3U
produces
http://cl.ly/1W0L0C423h2C0s103e2q

**Comment by ded** [comment]
patched. this should work now.
https://github.com/ded/bonzo/commit/9a04c9c3c4779c58c4b5f71c63637efdd93f157f

i'm going to close this now, but i will continue to fix this issue for other problematic elements. jQuery has a roundabout way of fixing this, but hopefully we can find something more elegant for our internals.
