### ISSUE TITLE
Bonzo Extension API

### ISSUE THREAD

**Issue by 84564221** [ded/bonzo#14]
```
Uncaught TypeError: Object [object HTMLParagraphElement],[object HTMLParagraphElement],[object HTMLParagraphElement],[object HTMLParagraphElement],[object HTMLParagraphElement],[object HTMLParagraphElement],[object HTMLParagraphElement] has no method 'color'
```

**Comment by ded** [comment]
oh, that's right. that was a doc mistake on my part. the <code>aug</code> method was designed for vanilla use of bonzo - however if you're using it with Ender, then you should use Ender's extension interface.

``` js
$.ender({
  color: function (c) {
    return this.css('color', c)
  }
}, true)
```

and that works of course when you're using Bonzo in Ender (expecting <code>this.css</code> to be defined)

cheers,
Dustin
