### ISSUE TITLE
bonzo.map is different to jQuery.map

### ISSUE THREAD

**Issue by joshski** [ded/bonzo#16]
bonzo.map() binds 'this' inside the callback to the current bonzo instance and passes the iterated element as the first argument to the callback. This is different from jQuery, which binds 'this' to the current element and passes the index as the first callback argument.

Bonzo also returns an array whereas jQuery returns a new jQuery object.

http://api.jquery.com/map/

Are these differences intended?

In general, is bonzo intended to behave like-for-like with jQuery where it defines functions with the same names?

Thanks

**Comment by fat** [comment]
imho, jQuery got it wrong here.

**Comment by ded** [comment]
yeah, i don't think we should be wrapping these objects in Ender objects (you can easily do it yourself tho). also, the nice thing about 'this' being the ender scope is that you can call elements on your own collection like `this.hasClass('foo')`
