### ISSUE TITLE
offset(0, 0)

### ISSUE THREAD

**Issue by pierrec** [ded/bonzo#17]
Hello,

When using the offset method with zeros for the coordinates, the method returns the offset position object instead of actually positioning the element.

I.e.
.offset(0, 0) returns { left: 123, right: 123, width: 123, height: 123 }

Cf. line 387
  if (x || y) {
should be something like
  if (x || y || x === 0) {

Cheers,

Pierre

**Comment by ded** [comment]
it should just check if they're typeof 'number' - thanks for the report
