### ISSUE TITLE
add support for .find() method if setQueryEngine has been called

### ISSUE THREAD

**Issue by micmath** [ded/bonzo#18]
If I have used setQueryEngine to add qwery to bonzo, the reference to qwery is kept in an inner variable that cannot be accessed from outside the bonzo object. I'd like to be able to chain a call to that qwery, like so:

``` javascript
$('ul').addClass('outer').find('li').addClass('inner');
```

Is this a useful feature generally? If so, I will be happy to provide a pull request.

**Comment by ded** [comment]
building with Ender will give you the `.find()`

**Comment by ded** [comment]
btw, if you're interested in how to get that stuff built, check the intro screencast at http://enderjs.com/learn
