### ISSUE TITLE
modify setQueryEngine to return reference to bonzo

### ISSUE THREAD

**Issue by micmath** [ded/bonzo#19]
Currently the setQueryEngine does not return any value, so if I want to add a query engine and then call noConflict, I have to write two lines of code. If setQueryEngine returned a reference to bonzo I could write a single chained line like so:

``` javascript
var q = window.qwery.noConflict(),
    b = window.bonzo.setQueryEngine(q).noConflict(); // chain!
```

**Comment by ded** [comment]
there was never a major priority for people to use Bonzo and Qwery as vanilla modules. For right now you'd be better of using Ender which handles all this stuff for you. Then you could just build them both:

```
$ ender build qwery bonzo
```

and then use it as such:

``` js
$('.content p').first().css('color', 'red')
```
