### ISSUE TITLE
val()

### ISSUE THREAD

**Issue by dvv** [ded/bonzo#3]
Hi!

`$('input')[0].attr('value', 'foo')` does nothing (at least in Chrome 9.0.597.94 on Linux 32-bit, debian 6.0). Instead, `$('input')[0].value = 'foo'` does work.

What is the way to robustly get/set `value` property of an elemnt in bonzo?

TIA,
--Vladimir

**Comment by ded** [comment]
hmmm... $("input.thing").val("wha") should work..

**Comment by dvv** [comment]
What line `.val` is defined at?

**Comment by ded** [comment]
https://github.com/ded/bonzo/blob/master/src/bonzo.js#L368

**Comment by dvv** [comment]
Ah, my file was older... Seems to be working. Thanks!

**Comment by ded** [comment]
again, thanks for being patient with all these. we're fixing bugs as we find them

**Comment by dvv** [comment]
np. btw, does `.val('')` clear the value of an input for you?

**Comment by ded** [comment]
yep
