### ISSUE TITLE
Support for replaceWith

### ISSUE THREAD

**Issue by martin-g** [ded/bonzo#30]
Hi,

I'd like to ask for support of a method that can replace a node with another node.
Currently I created this simple function:

```
$.ender({
    replaceWith: function(text) {
         return this.each(function (el) {
             var newEl = $.create(text);
             el.parentNode.replaceChild(newEl[0], el);
         });
    }
}, $);
```

but this method doesn't work for all cases and on all browsers.

For example

```
       $.domReady(function() {

            $('#table').bind('click', function(event) {

                var newHtml = 
                    "<table border='1'>"+
                        "<thead>"+
                            "<tr>"+
                                "<th>some head data</th>"+
                            "</tr>"+
                        "</thead>"+
                        "<tbody>"+
                            "<tr>"+
                                "<td>some data</td>"+
                            "</tr>"+
                        "</tbody>"+
                        "<tfoot>"+
                            "<tr>"+
                                "<td>some foot data</td>"+
                            "</tr>"+
                        "</tfoot>"+
                    "</table>"
                    ;
                $(this).replaceWith(newHtml);
            });

            $('#title').bind('click', function(event) {
                $('title').replaceWith("<title>new title</title>");
            });

            $('#script').bind('click', function(event) {
                var script = 
                    "<scr"+"ipt>console.log('inline');</scr"+"ipt>"+
                    "<scr"+"ipt src='outerHtml-script.js'></scr"+"ipt>"
                    ;
                $(this).replaceWith(script);
            });

        });
```
- replacing with a table seems to work on IE7,8,9, FF6 and Chrome 15.x.
- replacing the title fails on IE7,8.
- replacing with <script> doesn't execute the script body in none of the tested browsers.

Do you think such kind of functionality can be added to Bonzo ?

I need it to replace a custom solution which you can see at http://svn.apache.org/viewvc/wicket/trunk/wicket-core/src/main/java/org/apache/wicket/ajax/wicket-ajax.js?view=markup between lines 178 and 391. We'd like to replace this code with something provided by a JavaScript library specialized in DOM manipulation, like Bonzo.

**Comment by martin-g** [comment]
Sorry about the broken markup at the bottom of the issue. GitHub's Markdown decides that there is something special and breaks... I tried to fix it without success.

**Comment by ded** [comment]
i like the preliminary method you have. i can tell already where it will fail. it's the reason why i wrote this [tag map](https://github.com/ded/bonzo/blob/master/bonzo.js#L20). the issue with the title i feel less concerned on fixing considering you can do `$('title').html('new title')` instead of `$('title').replaceWith('<title>new title</title>')`

**Comment by martin-g** [comment]
Yes, we also do "document.title = 'new title'" now to workaround it.
The server side generates a complete html fragment for its client side representation.
The biggest problem is with the inline javascripts (e.g. &lt;div>&lt;script>alert(1);&lt;/script>&lt;/div>) because most of the browsers don't execute the body.
Actually I haven't checked what is the behavior of append/insert methods for this use case.

Well if you think such generic method (replaceWith) should not be included in Bonzo then just close the ticket as "Won't implement". It's OK.
Thanks!

**Comment by ded** [comment]
i'd love to add the generic replaceWith (as shown in your primary example), but not really go the extra mile to do the hackery to get it 100% crazy proof, especially given that there is more sane ways to do your other examples.
