### ISSUE TITLE
css opacity

### ISSUE THREAD

**Issue by paolochiodi** [ded/bonzo#4]
Setting the opacity of an element to 0 doesn't work.
I think it is due to the fact that 'px' is appended to 0.

**Comment by dawnerd** [comment]
How are you setting the css?  I just did this a few minutes ago and it worked fine using .css('opacity',0)

**Comment by paolochiodi** [comment]
oh, sorry. I was testing against yesterday npm version, not the master branch

**Comment by ded** [comment]
an aside, upgrade to the latest npm :)
then run

```
$ ender refresh
```

inside your custom build of Ender.
