### ISSUE TITLE
More intelligent hide/show/toggle

### ISSUE THREAD

**Issue by rvagg** [ded/bonzo#47]
`show()` uses `display=''` with possible override `type`
`toggle()` uses `display='block'` with no possible override

they should determine most appropriate display value for the particular element either from existing style information or perhaps by creating virgin elements and testing them and caching the values for each element type.

`hide()` should probably save the old display value so that can be restored by `show()`.

**Comment by ded** [comment]
with more intelligence comes a loss of speed. also, there's no true way of figuring this out — given the one case where an element could be `display:none` by default.

nevertheless, this _does_ bring up an issue that i need to fix, whereby toggle really should be using the internal `show`, passing along an override.

**Comment by ded** [comment]
should have referenced the commit, but i addressed this in the lastest push

**Comment by rvagg** [comment]
I guess that'll do for now but I'd still like to tackle some intelligence at some point to see how it goes. The default to `''` in `toggle()` is certainly a step forward!
