### ISSUE TITLE
`data('key')` where no data element for 'key' leave NaN

### ISSUE THREAD

**Issue by rvagg** [ded/bonzo#48]
``` js
  function dataValue(d) {
    try {
      return d === 'true' ? true : d === 'false' ? false : d === 'null' ? null : !isNaN(d) ? parseFloat(d) : d;
    } catch(e) {}
    return undefined
  }
```

is returning `NaN` for a bunch of `d` values where it should probably return something else, `undefined` or `null` probably. Most importantly these values give `NaN`: `''`, `null` (probably the culprit).

needs test cases.

yes, blame me.

**Comment by rvagg** [comment]
(updated description)

**Comment by ded** [comment]
indeed. test cases :)

**Comment by rvagg** [comment]
BTW this is my issue, I just need to find some time to write the tests & fix. Perhaps on the weekend.
