### ISSUE TITLE
#parents fails when no argument (Ender bridge)

### ISSUE THREAD

**Issue by benvinegar** [ded/bonzo#71]
```
$('body').parents();
> TypeError: Cannot read property 'nodeName' of undefined
```

For the moment I'm solving this by doing `$('body').parents('*')`.

I was going to create a unit test to demonstrate this, but I need #70 first. Not sure what the best approach is for doing pull requests w/ dependencies.

**Comment by rvagg** [comment]
you should use [Traversty](https://github.com/rvagg/traversty) btw
