### ISSUE TITLE
.next() .previous() add selectors

### ISSUE THREAD

**Issue by adamlukaszczyk** [ded/bonzo#73]
It would be nice to have possibility to use selectors inside the next and previous functions, for example to find next visible element or next element with the same class.

what do you think?

**Comment by rvagg** [comment]
http://github.com/rvagg/traversty

**Comment by ded** [comment]
woot. that!

**Comment by ded** [comment]
@dobiatowski what this means is you can add it to your ender bundle with `ender add traversty` and you should get what you desire

**Comment by adamlukaszczyk** [comment]
thx for pointing the way
