### ISSUE TITLE
Broken in current Ender (0.8.9)

### ISSUE THREAD

**Issue by deoxxa** [ded/bonzo#77]
After doing a simple `ender build bonzo` and creating a page that includes `ender.js`, in Chrome I am given this error:

```
Uncaught TypeError: Object #<Object> has no method 'setQueryEngine'
```

Seems to be that setQueryEngine is undefined on the object returned from require("bonzo") - even before it's first called.

**Comment by beatgammit** [comment]
+1 Noticed this today as well. Must be a problem with the bridge.

**Comment by carlyle** [comment]
+1 encountered this issue as well

**Comment by ded** [comment]
yep. i'm fixing it...

**Comment by ded** [comment]
k. this was broken from a recent commit to the ender client (not the CLI). patched earlier today. you guys should be good to go

**Comment by carlyle** [comment]
Working fine now, thanks

**Comment by ded** [comment]
rock on. i'm working on getting core Ender modules to compile well under Closure's advanced optimizations and hitting some bumps along the way

**Comment by deoxxa** [comment]
Awesome, thanks for the quick fix.
