### ISSUE TITLE
`.show()` doesn't work on an element with `.hide`

### ISSUE THREAD

**Issue by jonathanong** [ded/bonzo#78]
With `.hide` being the style `display: none;`

**Comment by ded** [comment]
it does.... however if the default style (from external css) is `display:none` - then you'll have to use `.show()` like this: `$('p').show('block')`

**Comment by jonathanong** [comment]
ah! this is actually solves some issues for me. shouldn't it be in the docs (the default style and it taking arguments)? thanks!
