### ISSUE TITLE
Selector for `children()` and `siblings()`

### ISSUE THREAD

**Issue by jonathanong** [ded/bonzo#79]
Do you guys have any plans to allow the `children()` and `siblings()` methods allow a `selector` argument for filtering? Also, a `filter()` method would be nice as well.

**Comment by ded** [comment]
this sounds ripe for a [traversty](https://github.com/rvagg/traversty) addition cc @rvagg.

**Comment by rvagg** [comment]
aye, I was just mulling this over this morning. I have tickets open for `children()`, `siblings()` and `parents()` using the same `([selector = "*"[, index = 0]])` argument syntax. I need to do something about them soon.

`filter()` is a new one on me but may be logical to put into the Qwery bridge? @amccollum has `$(x).matching(y)` as part of his [bridge](https://github.com/amccollum/sel/blob/master/src/extras/ender.coffee) for Sel which I believe would be roughly the equivalent.
