### ISSUE TITLE
comment about semicolon for concatenation tools breaks said concatenation tools

### ISSUE THREAD

**Issue by yorickvP** [ded/bonzo#89]
on the last line of bonzo.js:
`}, this); // the only line we care about using a semi-colon. placed here for concatenation tools`
currently, this breaks browserify (it assumes a newline on the end of the file)

This could be resolved by adding a newline to the file, or by turning the comment into a /**/ one.

**Comment by rvagg** [comment]
isn't this an issue for browserify? /cc @substack

**Comment by ded** [comment]
this is totally a bug in browserify. seems kind of silly to require a new line.
