### ISSUE TITLE
disable

### ISSUE THREAD

**Issue by dvv** [ded/bonzo#9]
Hi! How do I disable/enable elements with bonzo? TIA

**Comment by ded** [comment]
``` js
$('input[type=text]').attr('disabled', true);
```

**Comment by MartinodF** [comment]
Just in case anyone else in the future finds this issue while googling, here's how to re-enable elements:

```
$('input[disabled]').removeAttr('disabled');
```

`.attr('disabled', false)` will just set `disabled="false"`, which is still considered disabled in HTML5

**Comment by ded** [comment]
Github has the worst SEO juice, so it probably won't be a problem. But thanks for the tip :)

**Comment by MartinodF** [comment]
I have to agree, it took an `input disabled ender bonzo github` query to get this page as the **third** result, but that's how I got here in the first place, so there's always a chance ;) Thanks for the wonderful library!
